### ISSUE TITLE
Profile Widget not Showing in Mobile Aspect Ratio

### ISSUE THREAD

**Issue by arifyunando** [saicaca/hexo-theme-vivia#11]
## Problem:
Mobile aspect ratio not showing profile widget

## Expected behavior:
Profile widget shows at the bottom of the page

## Recreation step:
* Initiate theme
* Change window size to portrait

**Comment by saicaca** [comment]
Thank you for your feedback. It will be fixed later.

**Comment by saicaca** [comment]
Fixed in `v0.4.0`
