### ISSUE TITLE
如何自定义favicon和logo

### ISSUE THREAD

**Issue by deyuhu** [saicaca/hexo-theme-vivia#2]
首先感谢作者提供这么好看的主题 :tada::tada::tada:

我在 example_config.vivia.yml 中没有找到对应的配置，能否支持下。
![image](https://github.com/saicaca/hexo-theme-vivia/assets/62866504/bf56603f-f473-4811-b792-0fbb130ada42)

**Comment by saicaca** [comment]
感谢支持，favicon 可以在 `_config.vivia.yml` 设置，我忘记写在 example 里了。
```
favicon: /assets/favicon.png    # 将 /source/assets/favicon.png 设置为 favicon
```

导航栏的这个图标设计是临时的，我还没有决定是否要支持自定义图标，所以可能暂时不会加入这个功能，抱歉。
