### ISSUE TITLE
功能：调整页宽

### ISSUE THREAD

**Issue by OrionLi** [saicaca/hexo-theme-vivia#24]
对于一些高分辨率的大屏，文章两边会空出一大截。希望能加入宽屏模式

**Comment by OrionLi** [comment]
突然发现好像也不用那么麻烦，用户调下字体大小和网页缩放就行了

**Comment by AkiCCLing** [comment]
> 谢谢建议，目前方面我没有什么解决办法，因为页面主要内容的文本区域不可能拉太宽，否则会影响阅读效率。其他类似的网站也普遍存在你所说的问题，能否为你提供一些帮助觉得合适的翻译吗？

对于我的markdown表格来说，在当前的网页的页宽下显示效果十分糟糕
![hexo_blog_show](https://github.com/saicaca/hexo-theme-vivia/assets/53488343/68b9c6c2-732a-4b5d-81cb-d67d1b970d7e)

理想效果大概是这样
![my_blog_show](https://github.com/saicaca/hexo-theme-vivia/assets/53488343/fcae6e4d-7449-40be-96cc-3087e0d440c5)

**Comment by saicaca** [comment]
> 对于我的markdown表格来说，在当前的网页的页宽下显示效果十分糟糕

目前显示效果不堪入目的一大原因是单元格没有 padding，下个版本会修复这个问题。

至于页面宽度，目前文本区的宽度为820+px，其实已经比很多主题都要宽了，图中超过1000px的文本区宽度我觉得大多数情况下阅读体验并不好。如果确实需要增大页宽，暂时可以修改 `_variable.styl` 中的变量 `page-width = 1200px`
