### ISSUE TITLE
对主题页面配置文件的修改无效

### ISSUE THREAD

**Issue by hatsuyuki2333** [saicaca/hexo-theme-vivia#25]
嗯，我想在主页的某个地方添加Aplayer播放器，但是由于vivia通过npm安装，我又采取把hexo工作目录直接push到仓库，再由netlify编译静态页面的方式。git push默认忽略.node_modules（也不可能让它一起传上去）而vivia的页面配置文件`layout/*.ejs` 在这里面，所以本地做修改无效。有没有什么解决方法？
另外 考不考虑加入pjax支持？

**Comment by saicaca** [comment]
如果想修改主题本身的话，Hexo 有另一种不使用 npm 的主题安装方式，就是把主题文件放到 `/themes/vivia/` 目录里，你可以 clone 这个仓库或者先 fork 一个你的版本再 clone。后面的配置方式不变。

```bash
git clone https://github.com/saicaca/hexo-theme-vivia.git themes/vivia
```

关于 Pjax，目前我在用 Astro 重写这个项目，Astro 版本会用 ViewTransitions 实现类似单页面应用的效果。Hexo 版本以后我可能没有精力加入太多新功能了，所以为 Hexo 版本引入 Pjax 也不在计划内。

**Comment by hatsuyuki2333** [comment]
好的，谢谢了
