### ISSUE TITLE
功能：公式编辑

### ISSUE THREAD

**Issue by Antidington** [saicaca/hexo-theme-vivia#35]
我编辑了几个公式块但是没办法正常显示，请问是不支持公式块吗？
<img width="564" alt="image" src="https://github.com/saicaca/hexo-theme-vivia/assets/74341267/a96d9f99-9da3-4232-9941-7bc2404af56c">

**Comment by Movelocity** [comment]
可以换成hexo-renderer-markdown-it-plus来渲染，操作如下

1. `npm un hexo-renderer-marked --save`

2. `npm i @upupming/hexo-renderer-markdown-it-plus --save`

3. 找到模板的layout文件`layout.ejs`，在合适的地方加上 `<link href="https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/KaTeX/0.10.2/katex.min.css" rel="stylesheet">`

4. 配置文件加入相关配置
```yml
math:
  enable: true
  specific: false
  engine: katex
```

6. `hexo clean & hexo g`

**Comment by Antidington** [comment]
> 可以换成hexo-renderer-markdown-it-plus来渲染，操作如下
> 
> 1. `npm un hexo-renderer-marked --save`
> 2. `npm i @upupming/hexo-renderer-markdown-it-plus --save`
> 3. 找到模板的layout文件`layout.ejs`，在合适的地方加上 `<link href="https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/KaTeX/0.10.2/katex.min.css" rel="stylesheet">`
> 4. 配置文件加入相关配置
> 
> ```yaml
> math:
>   enable: true
>   specific: false
>   engine: katex
> ```
> 
> 6. `hexo clean & hexo g`

谢谢，已解决！😋
