### ISSUE TITLE
文章头图

### ISSUE THREAD

**Issue by lt-ainslee** [saicaca/hexo-theme-vivia#37]
![图片](https://github.com/saicaca/hexo-theme-vivia/assets/93432065/1049db8c-14e9-40c6-8d7c-e2493e84a457)
像这种头图是怎么做的啊，是在front-matter里面加一行什么配置吗

**Comment by 2b-creator** [comment]
请问如何做到的😂

**Comment by lt-ainslee** [comment]
修改对应文章front-matter配置，增添以下配置
```yaml
photos:        # img url
```
