### ISSUE TITLE
Bug:在部分分辨率屏幕下会导致屏幕右侧留白

### ISSUE THREAD

**Issue by HyperCherry** [saicaca/hexo-theme-vivia#42]
测试分辨率:`1025*753`（平板设备）

在某些分辨率中的屏幕中，若水平像素值不足以在`footer`右侧留下足够的缝隙，将会导致右侧出现一段留白
![image](https://github.com/saicaca/hexo-theme-vivia/assets/20416586/74cd80ba-5039-4d21-845d-381b33a90cf7)

https://github.com/saicaca/hexo-theme-vivia/blob/215aa41fd040268c45bfdc75d65feeb6343caf3c/source/css/_partial/back-to-top.styl#L1-L6

由于`right: -84px `将会导致右侧被强制撑开一段距离，造成留白，可以改为`right:0px`（紧靠`main_grid`）或者`position:fixed`+`right:0px`（紧靠全屏）来解决问题

这个问题在[Fuwari](https://github.com/saicaca/fuwari)中亦存在:[fuwari/src/components/control/BackToTop.astro](https://github.com/saicaca/fuwari/blob/4831f9f67f1d6a7f2c30c9efd63a0cba39bca91b/src/components/control/BackToTop.astro#L18-L23)

**Comment by saicaca** [comment]
感谢指出，主分支已修复
