### ISSUE TITLE
分類欄位顯示問題

### ISSUE THREAD

**Issue by FuseFairy** [saicaca/hexo-theme-vivia#43]
使用v0.4.2。
如題，文章實際上有被分類好，但是分類欄位顯示不出分類的標籤，除了在 ` _config.yml` 裡面編輯category_map，還有需要做其他設定嗎?謝謝

![image](https://github.com/saicaca/hexo-theme-vivia/assets/78064680/99647f1d-480b-42ab-88fd-5a9bdf5f530b)
![image](https://github.com/saicaca/hexo-theme-vivia/assets/78064680/25cdc879-8828-4f82-b453-4ae672cbdec9)

**Comment by saicaca** [comment]
已修复
