### ISSUE TITLE
分类栏无法显示分类

### ISSUE THREAD

**Issue by Jerryym** [saicaca/hexo-theme-vivia#48]
使用的主题版本为 0.4.2
Hexo version: 7.0.0
给文章设置了对应的分类，但是分类栏中无法显示对应分类，请问我应该如何解决？
![ABIH7SJS95{5M{3NHO}Y2WS](https://github.com/saicaca/hexo-theme-vivia/assets/36235101/77d9865c-0ce7-43ac-bda5-2abfbb5bf6da)

**Comment by saicaca** [comment]
Duplicate of #43

**Comment by saicaca** [comment]
参见 #43 ，暂时可通过降级 Hexo 至 6.3.0 解决，稍后会修复此问题

**Comment by Jerryym** [comment]
> 参见 #43 ，暂时可通过降级 Hexo 至 6.3.0 解决，稍后会修复此问题

好的，谢谢您
