### ISSUE TITLE
Plugin load failed: hexo-word-counter

### ISSUE THREAD

**Issue by EveSunMaple** [saicaca/hexo-theme-vivia#5]
作者大大您好，请问部署vercel报错
Plugin load failed: hexo-word-counter
Error: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /vercel/path0/node_modules/hexo-word-counter/index.node)
是什么原因呢。本地hexo s没有任何问题，问别人说vercel不支持这么底层的操作，这个主题不能部署在vercel上面吗。

![联想截图_20230711201759.png](https://img1.imgtp.com/2023/07/11/nnYeP3sG.png)

**Comment by 2b-creator** [comment]
> 作者大大您好，请问部署vercel报错 Plugin load failed: hexo-word-counter Error: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /vercel/path0/node_modules/hexo-word-counter/index.node) 是什么原因呢。本地hexo s没有任何问题，问别人说vercel不支持这么底层的操作，这个主题不能部署在vercel上面吗。
> 
> ![联想截图_20230711201759.png](https://camo.githubusercontent.com/a3d7e28c7fd1bbac4592d60a743160b799489de743abeb247f18fe053e385ced/68747470733a2f2f696d67312e696d6774702e636f6d2f323032332f30372f31312f6e6e5965503373472e706e67)

那个，我问个问题

您是要和别人协同完成文章还是自动编译站点？，我的建议是只部署网页与GitHub同步加速网页，不要把编译工具一股脑传上去在上面hexo s

vercel应该不支持这么做（本人以前就这么做过）

**Comment by EveSunMaple** [comment]
一股脑传上去是因为用来qexo，确实不太好😥
个人刚刚测试新开了一个项目也是这种情况，只能github静态部署吗

**Comment by 2b-creator** [comment]
> 一股脑传上去是因为用来qexo，确实不太好😥 个人刚刚测试新开了一个项目也是这种情况，只能github静态部署吗

明白了，glibc是linux底层的API库。通常情况下，有些环境需要glibc更高的版本才支持，比如你的GLIBC_2.28。
我猜vercel不支持底层的GLIBC_2.28更新，你没办法ssh碰不到系统底层

**Comment by EveSunMaple** [comment]
> > 一股脑传上去是因为用来qexo，确实不太好😥 个人刚刚测试新开了一个项目也是这种情况，只能github静态部署吗
> 
> 明白了，glibc是linux底层的API库。通常情况下，有些环境需要glibc更高的版本才支持，比如你的GLIBC_2.28。 我猜vercel不支持底层的GLIBC_2.28更新，你没办法ssh碰不到系统底层
> 
> 所以本地编译静态搞搞？或者等作者来😥

github静态部署成功了，不过这样就不支持qexo了，头疼😥

**Comment by saicaca** [comment]
抱歉，我目前不太了解 Vercel 部署，不知道如何解决此问题😥
如果只有 hexo-word-counter 无法导入的话可以暂时尝试移除 hexo-word-counter 的依赖并移除 `article.ejs` 中的字数统计 `symbolsCount(post)`

**Comment by HyperCherry** [comment]
这似乎的确是[Vercel的问题](https://github.com/orgs/vercel/discussions/3061#discussioncomment-6315667)，我使用这个主题在[netlify](https://www.netlify.com/)上面部署没有发生任何异常
你可以尝试把`hexo-word-counter`移除，并更换为[hexo-symbols-count-time](https://github.com/theme-next/hexo-symbols-count-time)应该能暂时让网页能够被部署到Vercel上
```
npm remove hexo-word-counter
npm install hexo-symbols-count-time
```
