### ISSUE TITLE
Bug : 分类 category-link 未定向 定向成了"/"

### ISSUE THREAD

**Issue by kismetpro** [saicaca/hexo-theme-vivia#50]
出逝 index.html
<img width="273" alt="屏幕截图 2023-12-14 124430" src="https://github.com/saicaca/hexo-theme-vivia/assets/83455616/491bae8b-78c2-4fa9-afa7-9d01f3eaa920">

应该定向为
<img width="240" alt="屏幕截图 2023-12-14 124444" src="https://github.com/saicaca/hexo-theme-vivia/assets/83455616/136e01bf-8241-40f5-bb70-6ba630eb7694">

**Comment by saicaca** [comment]
已修复
