### ISSUE TITLE
Bug: sidebar无法显示

### ISSUE THREAD

**Issue by Antidington** [saicaca/hexo-theme-vivia#51]
<img width="284" alt="image" src="https://github.com/saicaca/hexo-theme-vivia/assets/74341267/8dd67d62-f454-4d72-b439-cc68da1921ee">
请问这种情况怎么解决呀

**Comment by saicaca** [comment]
参考 #49 
是图标字体依赖的 CDN 出现故障，已经持续一段时间了，目前好像刚恢复。
鉴于这个 CDN 看起来维护状态不佳，下个版本会加入切换或关闭 CDN 的选项。
