### ISSUE TITLE
类型报错，但看不出来哪有问题（

### ISSUE THREAD

**Issue by shinichicun** [saicaca/hexo-theme-vivia#53]
你好，打扰了，我按照教程安装后，使用hexo g生成静态页面时会提示上述错误。但不知道是哪一步操作出了问题？
静待回复，非常感谢！
![image](https://github.com/saicaca/hexo-theme-vivia/assets/95010641/2ad9d491-2e71-43cf-9121-7350d4c262c7)
![image](https://github.com/saicaca/hexo-theme-vivia/assets/95010641/20029988-f0b4-4563-b360-90f8762e5fac)

**Comment by saicaca** [comment]
读取不到主题配置导致的，请参考安装过程第二步，检查是否将主题配置文件复制到 Hexo 博客的根目录并重命名为 `_config.vivia.yml`

**Comment by shinichicun** [comment]
搞出来了，十分感谢！！！
