### ISSUE TITLE
Markdown页内跳转跳不了

### ISSUE THREAD

**Issue by Lry722** [saicaca/hexo-theme-vivia#58]
是我的问题还是不支持？

大概就是有一节标题为
```
## 5. 构建写好的 Extension
```

在文章最后一行有这么一句
```
[构建写好的 Extension](#5-构建写好的-extension)
```

在本地用VSCode预览时是可以正常跳转的，但是部署后就不行了。

**Comment by saicaca** [comment]
看了一下，这个跳转似乎是大小写敏感的，无法跳转应该是因为你这里的 `Extension` 和 `extension` 大小写没对上

**Comment by Lry722** [comment]
@saicaca 试了一下确实可以😂
原先那个是VSCode自动补全出来的，看来不同平台对Markdown的支持还不太一致啊
