### ISSUE TITLE
关于Valine的配置

### ISSUE THREAD

**Issue by EveSunMaple** [saicaca/hexo-theme-vivia#6]
首先感谢作者提供这么好看的主题 🎉🎉🎉
关于Valine的配置，作者好像没有配置Valine的`severURLs`字段。
![联想截图_20230712080553.png](https://img1.imgtp.com/2023/07/12/prrKmut1.png)
现在问题是`Failed to load resource: net::ERR_CONNECTION_RESET`。
![联想截图_20230712080818.png](https://img1.imgtp.com/2023/07/12/HBHyUUgJ.png)
查阅了Valine的issue直接加` serverURLs: '<%= theme.valine.serverURLs %>' `会出现问题。
浏览了一圈vivia的站点好像也没有配置Valine的😥。

请问作者是如何在演示站配置Valine的呢，把us.leancloud.cn换成自己的域名不知道要怎么改

**Comment by EveSunMaple** [comment]
已解决，发现是我上面的配置写错了……
在"博客目录\node_modules\hexo-theme-vivia\layout\_partial\article.ejs"的第79行
添加`serverURLs: '<%= theme.comment.valine.serverURLs %>'`
然后在`_config.vivia.yml`添加自己的api域名就可以了
![联想截图_20230713071339.png](https://img1.imgtp.com/2023/07/13/AIqyuvbZ.png)
控制台无报错，Valine配置成功
不知道为什么作者没有添加severURLs字段
是否应该在下一次更新中加上🤨？

**Comment by saicaca** [comment]
😥感谢指出，之前开发时偷懒没把 Valine 的配置项写全，下次更新时会补上。如果你方便的话也可以发个 PR，非常感谢。
