### ISSUE TITLE
關於新增文章中嵌入youtube iframe影片

### ISSUE THREAD

**Issue by Lu-weiting** [saicaca/hexo-theme-vivia#62]
首先先感謝大大提供這麼頂的介面！

想詢問在文章中嵌入youtube iframe影片的效果該如何使用markdown寫出，我目前試過
1.  ```{% youtube wbm1a_0Pnd8 %}```
2. ```[![Canchu](https://i.ytimg.com/vi/wbm1a_0Pnd8/maxresdefault.jpg)](https://youtu.be/wbm1a_0Pnd8 "Canchu")```
3. <iframe src="https://youtu.be/wbm1a_0Pnd8" width="700px" height="500px" frameborder="0" scrolling="no"> </iframe>

只有第二種有顯示出來但是也不是像demo的模樣
第一種還會拋出unknown block tag: youtube這樣的錯誤

要怎麼有下面這種樣子（包含youtube的播放按鈕等等的
![截圖 2024-01-19 下午1 26 09](https://github.com/saicaca/hexo-theme-vivia/assets/128665065/c96a7bb5-c147-4bea-b857-12be6c8c1763)

**Comment by chunyiw8080** [comment]
第三种使用<iframe>标签是正确的写法啊，直接在youtube视频上点击复制嵌入代码就好了

**Comment by saicaca** [comment]
Demo 站用的是方法 1，沒有生效應該是因為 Hexo 從 7.0 版本開始不再自帶 YouTube Tag，需要自行安裝 `hexo-tag-embed`，詳見 https://hexo.io/docs/tag-plugins.html

**Comment by Lu-weiting** [comment]
> 第三种使用<iframe>标签是正确的写法啊，直接在youtube视频上点击复制嵌入代码就好了

**Comment by Lu-weiting** [comment]
> Demo 站用的是方法 1，沒有生效應該是因為 Hexo 從 7.0 版本開始不再自帶 YouTube Tag，需要自行安裝 `hexo-tag-embed`，詳見 https://hexo.io/docs/tag-plugins.html

感謝神作者，已解決
