### ISSUE TITLE
分类显示不完全

### ISSUE THREAD

**Issue by nicangtianws** [saicaca/hexo-theme-vivia#7]
您好，主页显示分类不全，只能显示两个分类，
![image](https://github.com/saicaca/hexo-theme-vivia/assets/40848997/275e4ef6-70d1-4573-a842-e6b8fefa5e39)

在build日志里面发现生成了对应分类的html文件
![image](https://github.com/saicaca/hexo-theme-vivia/assets/40848997/c5483f94-a086-4658-8cac-1871a907c710)

然后通过url访问也能进入
![image](https://github.com/saicaca/hexo-theme-vivia/assets/40848997/a1ef14b2-09df-4af6-ae81-6ad42a34bc9b)

在本地启动预览，则能正常显示。
![image](https://github.com/saicaca/hexo-theme-vivia/assets/40848997/3d3027c7-0308-49c7-8c12-fe1b180bd0f6)

请问这个怎么解决。

**Comment by nicangtianws** [comment]
网站是部署在netlify上的。

**Comment by saicaca** [comment]
大概知道原因了，现在目录树的生成函数是挂在 `generateBefore` 事件上的，但好像这时候通过 `hexo.locals` 拿到的目录列表并不完整，改成 `generateAfter` 好像就没问题了，晚点推一个版本修复。

**Comment by saicaca** [comment]
`v0.3.1` 已修复。
