### ISSUE TITLE
关于页面汉化的一个小问题

### ISSUE THREAD

**Issue by QBrer** [saicaca/hexo-theme-vivia#9]
最近在倒腾页面的时候，发现归档页面的这个Archive标题是固定的 ，想改成中文有点麻烦，需要到`node_modules/hexo-theme-vivia/layout/_partial/archive.ejs`进行修改，希望作者能把这个直接加到汉化里面
![屏幕截图 2023-08-02 173457](https://github.com/saicaca/hexo-theme-vivia/assets/94448088/f184ac1d-c668-493f-8182-891b3608db8d)

![屏幕截图 2023-08-02 174448](https://github.com/saicaca/hexo-theme-vivia/assets/94448088/64191bab-f80a-4892-b34f-592c5e6cfda9)

另外，真的真的特别喜欢这个主题，美炸了🥵

**Comment by saicaca** [comment]
感谢支持，下个版本会修复😺

**Comment by saicaca** [comment]
Fixed in `v0.4.0`
